{{- $chartName := include "helm-chart.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $chartName }}
data:
  domain: {{ .Values.config.domain | quote }}
  admin_email: {{ .Values.config.admin.email | quote }}
  smtp_host: {{ .Values.config.smtp.host | quote }}
  smtp_port: {{ .Values.config.smtp.port | quote }}
  smtp_secure: {{ .Values.config.smtp.secure | quote }}
  smtp_username: {{ .Values.config.smtp.username | quote }}
  kubernetes_namespace: {{ .Release.Namespace | quote }}
  kubernetes_storage_class: {{ .Values.config.kubernetes.storageClass | quote }}
  kubernetes_service_account: {{ $chartName }}
