apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.name" . }}
data:
  database_uri: {{ .Values.config.database.uri | b64enc }}
  admin_password: {{ .Values.config.admin.password | b64enc }}
  jwt_access_secret: {{ .Values.config.token.access.key | b64enc }}
  jwt_refresh_secret: {{ .Values.config.token.refresh.key | b64enc }}
  smtp_password: {{ .Values.config.smtp.password | b64enc }}
