{{- $chartName := include "helm-chart.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $chartName }}-ui
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app: {{ $chartName }}-ui
spec:
{{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
      app: {{ $chartName }}-ui
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
        app: {{ $chartName }}-ui
    spec:
      serviceAccountName: {{ $chartName }}
      containers:
        - name: {{ $chartName }}-ui
          image: "{{ .Values.image.agoracloud.ui.repository }}:{{ .Values.image.agoracloud.ui.tag }}"
          imagePullPolicy: {{ .Values.image.agoracloud.ui.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
