apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-chart.name" . }}
  labels: {{- include "helm-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "create", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["create", "bind", "escalate"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create"]
